### PR TITLE
Adding Attachment and Table Options

### PR DESCRIPTION
**Pull request by arcsector**
# Summary
This PR adds attachment and Table options for sending table or attachment-format results of a search to mattermost.

## Purpose
This is to give additional functionality by sending a greater number of results than just those used in the message.

## Additions
- `/bin/mattermost.py`
  - added functions:
    - `table_broker`
      - Checks for table or attachment selection and controls formatting, message contents, and attachment creation
    - `create_attachment_dict`
      - Creates a dictionary-formatted attachment dictionary to send to Mattermost API
    - `create_mm_field`
      - Helper function for `create_attachment_dict` to create [Mattermost Attachment Fields](https://docs.mattermost.com/developer/message-attachments.html#fields)
    - `create_markdown_separator`
      - Creates a markdown string that separates the header line and the data
    - `create_markdown_string`
      - Creates a markdown string from a csv list entry
    - `sanitize_results`
      - Sanitizes results so that no `__mv_` fields make it in the table
    - `sanitize_list`
      - Sanitizes table fieldnames to remove `__mv_` fields
    - `delete_key`
      - Deletes a key in a dictionary and returns the dictionary because there's no idiomatic, pythonic way to do this in a one-liner and without using nested loops

## Changes
- `/bin/mattermost.py`
  - `send_notification`
    - Params now the message, url, and optional attachment dictionary
- `/default/data/ui/alerts/mattermost.html`
  - Added table and attach select group

### CODE REVIEW

**Comment by arcsector** [comment]
Sorry about the crazy commit history; i had to nuke the repo because of committing `temp.csv`.

**Comment by couloum** [comment]
Hi @arcsector . Thanks for this PR. I'll test the new version and will merge if everything works fine on my side.

**Comment by couloum** [comment]
I tried this new plugin with simple alert `index="_internal" | top component`.

I got the following result with `table` mode:

image

The column `_tc` should not be part of my results. I'm using Splunk 6.4.0. With what version of Splunk have you tested?


Regarding the `attachment` type, I did not find a link to download the file in my alert:

image

Is this output normal?

Thanks

**Comment by arcsector** [comment]
Hi @couloum; to answer your questions:
1. I'm not sure what _tc is... I can't find any documentation regarding that field, but _maybe we should exclude it manually..._ What do you think?
2. Attachment is a misnomer in mattermost, see this Mattermost documentation [link](https://docs.mattermost.com/developer/message-attachments.html); it is a port of Slack's attachment message type. _Let me know how i can clarify the terminology to make it clear this is not an actual file attachment, but an attachment table._

**Comment by couloum** [comment]
1. Yes, I think we can manually exclude `_tc` field. I tried, using the same logic as `__mv_`, but it didn't work. Maybe I'm missing something.

2. Oh, ok. I don't use this feature from Mattermost so I though it was an actual file attachment. Maybe we should reuse the term "Message attachment" from the link you provided.

Can you edit the PR with these changes?

Thanks

**Comment by arcsector** [comment]
@couloum Done; copying commit message here:
- Adding `_tc` field to `sanitize_results` and `sanitize_list`
- Clarifying "Message Attachment" in alert selection in html

**Comment by arcsector** [comment]
Adding python3 support

**Comment by arcsector** [comment]
Closing as stale

**Pull request closed without merging**
